name: 'Build Kernel & UBoot'
on:
  push:
    paths:
      - 'CHANGES'
  workflow_dispatch:

jobs:
  build-kernel-and-uboot:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Toolchains
        run: |
          wget https://github.com/sensors-link/NUC970_Toolchain/releases/download/v1.0.0/arm_linux_4.8.tar.gz
          wget https://github.com/sensors-link/NUC970_Toolchain/releases/download/v1.0.0/toolchain_install.sh
          sudo sh toolchain_install.sh
          export PATH=/usr/local/arm_linux_4.8/bin:$PATH
          ls /usr/local/arm_linux_4.8
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: configure
        run: |
          make slink_uitd_defconfig
      - name: make kernel & uboot
        run: |
          make linux
          make uboot
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bsp
          path: |
            output/images/u-boot*
            output/images/uImage
