name: 'Build Kernel & UBoot'
on:
  push:
    paths:
      - '.github/workflows/build-kernel-and-uboot.yml'
  workflow_dispatch:

jobs:
  build-kernel-and-uboot:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Toolchains
        run: |
          wget -q https://github.com/sensors-link/NUC970_Toolchain/releases/download/v1.0.0/arm_linux_4.8.tar.gz
          wget -q https://github.com/sensors-link/NUC970_Toolchain/releases/download/v1.0.0/toolchain_install.sh
          sudo bash toolchain_install.sh
          export PATH=/usr/local/arm_linux_4.8/bin:$PATH
          ls /usr/local/arm_linux_4.8
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Patch Toolchain with kernel-headers
        run: |          
          wget -q -P dl https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.10.108.tar.xz
          tar Jxvf dl/linux-3.10.108.tar.xz
          cd linux-3.10.108; make headers_install; cd ..
          sudo ln -s `pwd`/linux-3.10.108/usr/include/linux /usr/local/arm_linux_4.8/usr/include/linux
      - name: Configure buildroot with defconfig
        run: |
          make slink_rootfs_defconfig
      - name: Make rootfs
        run: |
          make
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rootfs
          path: |
            !output/images/u-boot*
            !output/images/uImage
